language: python
python:
  - "3.6.6"
install:
  - cp contrib/env-sample .env
  - pip install -r requirements-dev.txt
script:
  - pycodestyle pybling/
  - pyflakes pybling/
  - python -m doctest README.md -v
  - pytest tests/tests.py --verbosity=1
